### ISSUE TITLE
Any reference papers to start?

### ISSUE THREAD

**Issue by Guowu-Mcgill** [mghasemi/Irene#1]
Hi mghasemi,

Thanks for sharing this package, Irene. It looks very interesting. However, if it includes some reference, like theory behind and demonstrations, I am sure it will help people, especially beginner to understand. Thanks!

**Comment by mghasemi** [comment]
Sure! References are included in the documentation. The one that helped the development of the package is the book "Moments, Positive Polynomials, and their Applications"  by J. B. Lasserre. https://link.springer.com/article/10.1007/s10208-011-9092-6

**Comment by Guowu-Mcgill** [comment]
Hi mghasemi,

Thanks a lot for this prompt and kindly reply. I appreciate!

Regards,
Guowu
